language: perl

matrix:
    include:
        - os: linux
        - os: osx

dist: trusty

perl:
    - "5.24"
    - "5.18"
    - "5.16"
    - "5.08"

install: true

script: cd bin ; ./mh -tk 0 -code_dir ../code/test
